SELECT 
	C.ID_CLIENTE, 
    C.RAZAO_SOCIAL,
    COALESCE(SUM(P.VALOR_TOTAL), 0) AS TOTAL
FROM 
	CLIENTES C
LEFT JOIN 
	PEDIDO P on C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.ID_CLIENTE
ORDER BY TOTAL DESC