SELECT 
	P.ID_PEDIDO AS id,
	P.VALOR_TOTAL AS valor,
	P.DATA_EMISSAO AS data,
CASE 
	WHEN P.DATA_CANCELAMENTO is not null THEN 'CANCELADO'
	WHEN P.DATA_FATURAMENTO IS NOT null THEN 'FATURADO'
	ELSE 'PENDENTE'
END AS situacao
FROM PEDIDO P
