SELECT 
    V.ID_VENDEDOR AS id, 
    V.NOME AS nome, 
    V.SALARIO AS salario 
FROM 
    VENDEDORES V
WHERE 
    V.SALARIO > (SELECT AVG(SALARIO) FROM VENDEDORES)
ORDER BY 
    V.SALARIO DESC