SELECT
	I.ID_PRODUTO AS id_produto,
    SUM(I.QUANTIDADE) as quantidade_vendida,
    SUM(I.PRECO_PRATICADO * I.QUANTIDADE) as total_vendido,
    count(I.ID_PEDIDO) as pedidos,
    count(DISTINCT P.ID_CLIENTE) as clientes
FROM ITENS_PEDIDO I
JOIN PEDIDO p on I.ID_PEDIDO = P.ID_PEDIDO
GROUP BY I.ID_PRODUTO
ORDER BY
    QUANTIDADE_VENDIDA DESC,
    TOTAL_VENDIDO DESC
LIMIT 1;